# Generated by Django 3.1.1 on 2020-09-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200905_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(null=True, related_name='classes', related_query_name='classes', to='classroom.Student'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='classroom.class'),
        ),
    ]
