# Generated by Django 3.1.1 on 2020-09-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='quiz',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='classroom.quiz'),
            preserve_default=False,
        ),
    ]
